package main

import (
	"crypto/sha256"
	"encoding/base64"
	"encoding/hex"
	"fmt"
)

// This file implements the pure, non-network parts of the Sky Stream / Sky
// Glass remote control protocol: message shapes, auth token derivation, and
// the button-to-key-name mapping. The protocol itself was reverse-engineered
// from the official "Sky Remote" Android app by
// https://github.com/jatatech/sky_stream_remote (see
// Docs/SKY_REMOTE_PROTOCOL.md in that repo for the full writeup this is
// ported from). That repo carries no license file, so nothing is copied
// from it verbatim - this is an independent implementation of the documented
// protocol, the same way skyq.go independently implements the Sky Q protocol
// documented by github.com/dalhundal/sky-remote.
//
// The protocol requires an mTLS client certificate/key pair that is shared
// across every install of the official app (not per-user, not generated by
// this code). Slinky does not vendor or embed those credentials - see
// docs/plans/sky-stream-support.md for how they're expected to be supplied.

const (
	skyStreamCommandPairRequest       = "Pair Request"
	skyStreamCommandBindRequest       = "Bind Request"
	skyStreamCommandKeyCommandRequest = "Key Command Request"

	skyStreamManufacturer = "Comcast"
	skyStreamModel        = "IPRemote"
	skyStreamKeyCmd       = "keyatomic"

	// skyStreamAuthTokenSalt is a hardcoded salt found in the official
	// app's binary; it's a fixed input to the auth token derivation, not a
	// secret this codebase controls.
	skyStreamAuthTokenSalt = "biT43y"
)

// skyStreamPairRequest is sent by the client to begin pairing.
type skyStreamPairRequest struct {
	CommandName     string `json:"command_name"`
	TID             string `json:"tid"`
	Name            string `json:"name"`
	Manufacturer    string `json:"manufacturer"`
	Model           string `json:"model"`
	ControllerNonce string `json:"controllernonce"`
}

// skyStreamPairResponse is the STB's reply to a pair request.
type skyStreamPairResponse struct {
	CommandName string `json:"command_name"`
	Name        string `json:"name"`
	PairingCode string `json:"pairingcode"`
	Status      bool   `json:"status"`
	STBNonce    string `json:"stbnonce"`
	TID         string `json:"tid"`
}

// skyStreamBindRequest authenticates the client using the derived auth
// token.
type skyStreamBindRequest struct {
	CommandName string `json:"command_name"`
	TID         string `json:"tid"`
	AuthToken   string `json:"authtoken"`
}

// skyStreamBindResponse carries the bind_id needed for subsequent commands
// on success; Status is false (with no bind_id) on failure.
type skyStreamBindResponse struct {
	CommandName string `json:"command_name"`
	Status      bool   `json:"status"`
	BindID      int    `json:"bind_id"`
	TID         string `json:"tid"`
}

// skyStreamKeyCommandRequest sends a single button press.
type skyStreamKeyCommandRequest struct {
	CommandName string `json:"command_name"`
	TID         string `json:"tid"`
	AuthToken   string `json:"authtoken"`
	BindID      int    `json:"bind_id"`
	Cmd         string `json:"cmd"`
	Key         string `json:"key"`
}

// skyStreamKeyCommandResponse is the STB's reply to a key command. Error is
// set (e.g. to "unrecognized") when the key name isn't supported.
type skyStreamKeyCommandResponse struct {
	CommandName string `json:"command_name"`
	Status      bool   `json:"status"`
	TID         string `json:"tid"`
	Error       string `json:"error,omitempty"`
}

// computeSkyStreamAuthToken derives the auth token proving the client's
// identity to the STB, per Docs/SKY_REMOTE_PROTOCOL.md section 6:
//
//	inner = SHA256(cert_fingerprint_bytes ‖ pairingcode ‖ controllernonce)
//	token = Base64(SHA256(stbnonce ‖ inner ‖ "biT43y"))
//
// certFingerprint is the 64-character lowercase hex SHA-256 fingerprint of
// the client certificate's DER encoding.
func computeSkyStreamAuthToken(certFingerprint, pairingCode, controllerNonce, stbNonce string) (string, error) {
	fp, err := hex.DecodeString(certFingerprint)
	if err != nil {
		return "", fmt.Errorf("invalid cert fingerprint: %w", err)
	}

	stage1 := make([]byte, 0, len(fp)+len(pairingCode)+len(controllerNonce))
	stage1 = append(stage1, fp...)
	stage1 = append(stage1, []byte(pairingCode)...)
	stage1 = append(stage1, []byte(controllerNonce)...)
	inner := sha256.Sum256(stage1)

	stage2 := make([]byte, 0, len(stbNonce)+len(inner)+len(skyStreamAuthTokenSalt))
	stage2 = append(stage2, []byte(stbNonce)...)
	stage2 = append(stage2, inner[:]...)
	stage2 = append(stage2, []byte(skyStreamAuthTokenSalt)...)
	final := sha256.Sum256(stage2)

	return base64.StdEncoding.EncodeToString(final[:]), nil
}

// skyStreamKeys maps Slinky's existing remote button IDs (see
// html/remote.html, and skyCommands in skyq.go for the Sky Q equivalent) to
// the key names the Sky Stream protocol expects. volume-up/volume-down/mute
// are intentionally absent: they're handled client-side against the
// <video> element and never reach a control backend, same as with skyq and
// harmony today.
//
// "menu" maps to Home, confirmed against a real box - the physical remote's
// menu button behaves as "go to home screen", not AccessMenu ("more").
// "return" maps to Dismiss - Backspace was tried first (per the protocol
// doc's description) but didn't behave as "back" in practice. Dismiss is
// the only other candidate in the documented key vocabulary; not yet
// confirmed against real hardware.
var skyStreamKeys = map[string]string{
	"power":  "Power",
	"select": "Enter",
	"return": "Dismiss",

	"channel-up":   "ChannelUp",
	"channel-down": "ChannelDown",

	"info":   "Info",
	"search": "Search",
	"menu":   "Home",

	"direction-up":    "ArrowUp",
	"direction-down":  "ArrowDown",
	"direction-left":  "ArrowLeft",
	"direction-right": "ArrowRight",

	"red":    "Red",
	"green":  "Green",
	"yellow": "Yellow",
	"blue":   "Blue",

	"0": "Digit0",
	"1": "Digit1",
	"2": "Digit2",
	"3": "Digit3",
	"4": "Digit4",
	"5": "Digit5",
	"6": "Digit6",
	"7": "Digit7",
	"8": "Digit8",
	"9": "Digit9",

	"play":         "MediaPlay",
	"rewind":       "MediaRewind",
	"fast-forward": "MediaFastForward",
	"record":       "MediaRecord",
}
