port: 8080
control: harmony
sky_q:
  host: 10.86.0.205
  port: 49160
harmony_api:
  url: http://10.86.0.10:8282
  hubs:
    - name: kitchen
      activities:
        - watch-tv
  default_hub: kitchen
  default_activity: watch-tv
stream:
  quality:
    - name: High (hevc)
      location: /stream/0.ts
      default: true
    - name: High (h.264)
      location: /stream/1.ts
    - name: Medium (hevc)
      location: /stream/2.ts
    - name: Low (hevc)
      location: /stream/3.ts
  hls:
  - name: "1080p"
    location: "/stream/0.m3u8"
    bandwidth: 8000000
    resolution: 1920x1080
    codecs: "hvc1.1.6.L120.B0,mp4a.40.2"
    frame_rate: 25.000
  - name: "720p"
    location: "/stream/1.m3u8"
    bandwidth: 4000000
    resolution: 1280x720
    codecs: "hvc1.1.6.L120.B0,mp4a.40.2"
    frame_rate: 25.000
  - name: "480p"
    location: "/stream/2.m3u8"
    bandwidth: 1500000
    resolution: 854x480
    codecs: "hvc1.1.6.L120.B0,mp4a.40.2"
    frame_rate: 25.000
  - name: "360p"
    location: "/stream/3.m3u8"
    bandwidth: 750000
    resolution: 640x360
    codecs: "hvc1.1.6.L120.B0,mp4a.40.2"
    frame_rate: 25.000
dev:
  enabled: false
  stream: http://10.86.0.20:8086
