port: 8080
harmony_api:
  url: http://10.86.0.10:8282
  hubs:
    - name: kitchen
      activities:
        - watch-tv
  default_hub: kitchen
  default_activity: watch-tv
stream:
  quality:
    - name: Very High
      location: /0.ts
      default: true
    - name: High
      location: /1.ts
    - name: Medium
      location: /2.ts
    - name: Low
      location: /3.ts
dev:
  enabled: false
  stream: http://10.86.0.20:8086