port: 8080
harmony_api:
  url: http://10.86.0.10:8282
  hubs:
    - name: kitchen
      activities:
        - watch-tv
  default_hub: kitchen
  default_activity: watch-tv
stream:
  quality:
    - name: High
      location: /stream/1.m3u8
    - name: Medium
      location: /stream/2.m3u8
    - name: Low
      location: /stream/2.m3u8
      default: true
dev:
  enabled: false
  stream: http://10.86.0.20:8086