stream:
  quality:
    - name: High
      location: /1.m3u8
    - name: Medium
      location: /2.m3u8
    - name: Low
      location: /3.m3u8
      default: true
    - name: Instant
      location: /3.flv