port: 8080
control: harmony
sky_q:
  host: 10.86.0.205
  port: 49160
harmony_api:
  url: http://10.86.0.10:8282
  hubs:
    - name: kitchen
      activities:
        - watch-tv
  default_hub: kitchen
  default_activity: watch-tv
stream:
  quality:
    - name: High (hevc)
      location: /stream/0.ts
      default: true
    - name: High (h.264)
      location: /stream/1.ts
      default: true
    - name: Medium (hevc)
      location: /stream/2.ts
    - name: Low (hevc)
      location: /stream/3.ts
dev:
  enabled: false
  stream: http://10.86.0.20:8086
