stream:
  quality:
    - name: Very High
      location: /0.ts
      default: true
    - name: High
      location: /1.ts
    - name: Medium
      location: /2.ts
    - name: Low
      location: /3.ts
